# Generated by Django 5.2 on 2025-04-28 18:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('REPLIED', 'Replied')], default='UNREAD', max_length=20)),
                ('is_deleted_by_sender', models.BooleanField(default=False)),
                ('is_deleted_by_receiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Tracks last update')),
                ('edited_at', models.DateTimeField(auto_now=True, db_comment='Tracks last edit')),
            ],
            options={
                'db_table': 'chats',
                'db_table_comment': 'Stores private Chat Forum messages',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('reaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('LIKE', 'Like'), ('LOVE', 'Love'), ('HAHA', 'Haha'), ('WOW', 'Wow'), ('SAD', 'Sad')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message_reactions',
                'db_table_comment': 'Stores reactions to private and society messages',
            },
        ),
    ]
