# Generated by Django 5.2 on 2025-04-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chats",
            name="book",
            field=models.ForeignKey(
                blank=True,
                db_comment="Links to ExchangeNow swaps for contextual chats",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="library.books",
            ),
        ),
        migrations.AddField(
            model_name="chats",
            name="parent_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="chat.chats",
            ),
        ),
    ]
