# Generated by Django 5.2 on 2025-04-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='book',
            field=models.ForeignKey(blank=True, db_comment='Links to ExchangeNow swaps', null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.book'),
        ),
    ]
