# Generated by Django 5.2 on 2025-05-21 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
        ('discussions', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='reaction_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('LOVE', 'Love'), ('HAHA', 'Haha'), ('WOW', 'Wow'), ('SAD', 'Sad'), ('ANGRY', 'Angry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user'], name='message_rea_user_id_565363_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chat__isnull', False), ('society_message__isnull', True)), models.Q(('chat__isnull', True), ('society_message__isnull', False)), _connector='OR'), name='one_message_type'),
        ),
    ]
