# Generated by Django 5.2 on 2025-04-28 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "reaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("LIKE", "Like"),
                            ("LOVE", "Love"),
                            ("HAHA", "Haha"),
                            ("WOW", "Wow"),
                            ("SAD", "Sad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "message_reactions",
                "db_table_comment": "Stores reactions to private and society messages",
            },
        ),
        migrations.RemoveField(
            model_name="societies",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="societymembers",
            name="society",
        ),
        migrations.RemoveField(
            model_name="societymessages",
            name="society",
        ),
        migrations.AlterUniqueTogether(
            name="societymembers",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="societymembers",
            name="user",
        ),
        migrations.RemoveField(
            model_name="societymessages",
            name="book",
        ),
        migrations.RemoveField(
            model_name="societymessages",
            name="user",
        ),
        migrations.RemoveField(
            model_name="chats",
            name="parent_chat",
        ),
        migrations.AddField(
            model_name="chats",
            name="edited_at",
            field=models.DateTimeField(auto_now=True, db_comment="Tracks last edit"),
        ),
    ]
