# Generated by Django 5.2 on 2025-06-25 03:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_messagereaction_reaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='media_duration',
            field=models.IntegerField(blank=True, db_comment='Duration in seconds for audio/video', null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='media_filename',
            field=models.CharField(blank=True, db_comment='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='media_size',
            field=models.BigIntegerField(blank=True, db_comment='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='media_thumbnail',
            field=models.URLField(blank=True, db_comment='Thumbnail for videos/images', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='media_url',
            field=models.URLField(blank=True, db_comment='URL for uploaded media files', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('VOICE_NOTE', 'Voice Note'), ('BOOK_REFERENCE', 'Book Reference'), ('FILE', 'File')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='chats',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chats',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('REPLIED', 'Replied')], default='SENT', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatTypingStatus',
            fields=[
                ('typing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_typing', models.BooleanField(default=False)),
                ('last_typing_at', models.DateTimeField(auto_now=True)),
                ('chat_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_typing_statuses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_typing_status',
                'indexes': [models.Index(fields=['user', 'chat_partner'], name='chat_typing_user_id_921df0_idx'), models.Index(fields=['last_typing_at'], name='chat_typing_last_ty_c3b9a8_idx')],
                'unique_together': {('user', 'chat_partner')},
            },
        ),
    ]
