# Generated by Django 5.2 on 2025-04-28 05:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_messagereaction_remove_societies_creator_and_more"),
        ("discussions", "0004_discussion_note_reprint_society_societyevent_and_more"),
        (
            "library",
            "0003_book_bookmark_favorite_library_remove_bookmarks_book_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chats",
            name="book",
            field=models.ForeignKey(
                blank=True,
                db_comment="Links to ExchangeNow swaps",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.book",
            ),
        ),
        migrations.AlterField(
            model_name="chats",
            name="chat_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="chats",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="chats",
            name="is_deleted_by_receiver",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chats",
            name="is_deleted_by_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chats",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chats",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chats",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNREAD", "Unread"),
                    ("READ", "Read"),
                    ("REPLIED", "Replied"),
                ],
                default="UNREAD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chats",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="Tracks last update",
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="chats",
            index=models.Index(
                fields=["sender", "receiver"], name="chats_sender__acde62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chats",
            index=models.Index(fields=["created_at"], name="chats_created_e8f0e7_idx"),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="chat.chats",
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="society_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="discussions.societymessage",
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Societies",
        ),
        migrations.DeleteModel(
            name="SocietyMembers",
        ),
        migrations.DeleteModel(
            name="SocietyMessages",
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(fields=["chat"], name="message_rea_chat_id_016b0c_idx"),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["society_message"], name="message_rea_society_5cdd84_idx"
            ),
        ),
    ]
