# Generated by Django 5.2 on 2025-05-20 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_initial'),
        ('swaps', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='notification',
            table_comment='Sends alerts for swaps, messages, and other events',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_id',
            field=models.UUIDField(blank=True, db_comment='ID of the related content (e.g., chat_id)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.CharField(blank=True, db_comment='Type of content (e.g., chat, society_message)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('swap_proposed', 'Swap Proposed'), ('swap_accepted', 'Swap Accepted'), ('swap_confirmed', 'Swap Confirmed'), ('swap_completed', 'Swap Completed'), ('swap_cancelled', 'Swap Cancelled'), ('message_received', 'Message Received')], db_comment='Type of notification for UI and tracking', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'content_id'], name='notificatio_content_393656_idx'),
        ),
    ]
