# Generated by Django 5.2 on 2025-05-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0003_alter_notification_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('swap_proposed', 'Swap Proposed'), ('swap_accepted', 'Swap Accepted'), ('swap_confirmed', 'Swap Confirmed'), ('swap_completed', 'Swap Completed'), ('swap_cancelled', 'Swap Cancelled'), ('message_received', 'Message Received'), ('message_edited', 'Message Edited')], db_comment='Type of notification for UI and tracking', max_length=50),
        ),
    ]
