# Generated by Django 5.2 on 2025-05-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('swap_proposed', 'Swap Proposed'), ('swap_accepted', 'Swap Accepted'), ('swap_confirmed', 'Swap Confirmed'), ('swap_completed', 'Swap Completed'), ('swap_cancelled', 'Swap Cancelled'), ('message_received', 'Message Received'), ('message_edited', 'Message Edited'), ('message_read', 'Message Read')], db_comment='Type of notification for UI and tracking', max_length=50),
        ),
    ]
