# Generated by Django 5.2 on 2025-04-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discussions", "0001_initial"),
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussions",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="library.books",
            ),
        ),
    ]
