# Generated by Django 5.2 on 2025-04-28 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0004_discussion_note_reprint_society_societyevent_and_more"),
        (
            "library",
            "0003_book_bookmark_favorite_library_remove_bookmarks_book_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.book",
            ),
        ),
        migrations.AddField(
            model_name="discussion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="discussion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="discussions.discussion",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="parent_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="discussions.note",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="reprint",
            name="discussion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reprints",
                to="discussions.discussion",
            ),
        ),
        migrations.AddField(
            model_name="reprint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="society",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="societyevent",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.book",
            ),
        ),
        migrations.AddField(
            model_name="societyevent",
            name="society",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="discussions.society",
            ),
        ),
        migrations.AddField(
            model_name="societymember",
            name="society",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="discussions.society",
            ),
        ),
        migrations.AddField(
            model_name="societymember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="societymessage",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.book",
            ),
        ),
        migrations.AddField(
            model_name="societymessage",
            name="society",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="discussions.society",
            ),
        ),
        migrations.AddField(
            model_name="societymessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Discussions",
        ),
        migrations.DeleteModel(
            name="Notes",
        ),
        migrations.DeleteModel(
            name="Reprints",
        ),
        migrations.AddIndex(
            model_name="society",
            index=models.Index(
                fields=["focus_type", "focus_id"], name="societies_focus_t_871775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="societymember",
            index=models.Index(
                fields=["society", "user"], name="society_mem_society_00dceb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="societymember",
            unique_together={("society", "user")},
        ),
        migrations.AddIndex(
            model_name="societymessage",
            index=models.Index(
                fields=["society"], name="society_mes_society_070b7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="societymessage",
            index=models.Index(
                fields=["created_at"], name="society_mes_created_5cfaef_idx"
            ),
        ),
    ]
