# Generated by Django 5.2 on 2025-05-23 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_remove_note_likes_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='reprint',
            table_comment='Stores discussion reprints',
        ),
        migrations.AlterField(
            model_name='reprint',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='reprint',
            unique_together={('discussion', 'user')},
        ),
        migrations.AddIndex(
            model_name='reprint',
            index=models.Index(fields=['discussion', 'user'], name='reprints_discuss_73743d_idx'),
        ),
    ]
