# Generated by Django 5.2 on 2025-06-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_downvote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='downvote',
            new_name='downvotes_discuss_76be57_idx',
            old_name='downvotes_discuss_user_idx',
        ),
    ]
