# Generated by Django 5.2 on 2025-04-28 05:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follows",
            fields=[
                (
                    "follow_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_mutual",
                    models.BooleanField(
                        default=False,
                        help_text="Precomputed mutual status to accelerate chat unlocks",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft deletion for unfollow events, keeps social history",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Search", "Search"),
                            ("Swap", "Swap"),
                            ("Chat", "Chat"),
                            ("Recommendation", "Recommendation"),
                        ],
                        default="Search",
                        help_text="Origin of follow for funnel analysis and personalization",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "follows",
                "db_table_comment": "Manages user follows to drive chats, personalization, and feed logic",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        13, message="Users must be at least 13 years old"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="chat_preferences",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="ethnicity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="genres",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["username"], name="idx_users_username"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="idx_users_email"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["city"], name="idx_users_city"),
        ),
        migrations.AddField(
            model_name="follows",
            name="followed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follows",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="follows",
            index=models.Index(fields=["follower"], name="idx_follows_follower_id"),
        ),
        migrations.AddIndex(
            model_name="follows",
            index=models.Index(fields=["followed"], name="idx_follows_followed_id"),
        ),
        migrations.AlterUniqueTogether(
            name="follows",
            unique_together={("follower", "followed")},
        ),
    ]
